apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutriapp-deployment
  labels:
    app: nutriapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nutriapp
  template:
    metadata:
      labels:
        app: nutriapp
    spec:
      containers:
      - name: nutriapp
        image: bhagatritwik/nutritrack:v1
        ports:
        - containerPort: 80