apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutriapp-deployment
  labels:
    app: nutriapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nutriapp
  template:
    metadata:
      labels:
        app: nutriapp
    spec:
      containers:
      - name: nutriapp
        image: bhagatritwik/nutritrack:v1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nutriapp-service
spec:
  type: NodePort
  selector:
    app: nutriapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001  
    protocol: TCP